--SELECT  G.GENRE,M.TITLE,M.ORIGINAL_TITLE,M.RELEASE_DATE INTO #tmpGG
--FROM MOVIE M 
--INNER JOIN MOVIE_GENRE MG ON MG.FILMID=M.FILMID
--INNER JOIN GENRE G ON G.GENREID=MG.GENREID
--At the upper command line, I created a TemporaryTable named #tmpGG for using in the subqueries.



SELECT  YEAR(GN.RELEASE_DATE) Year_,
(SELECT COUNT(DISTINCT TITLE) FROM #tmpGENRE WHERE GENRE LIKE 'Action' AND YEAR(RELEASE_DATE)=YEAR(GN.RELEASE_DATE)) #ofACTIONMovies,
(SELECT COUNT(DISTINCT TITLE) FROM #tmpGENRE WHERE GENRE LIKE 'Adventure' AND YEAR(RELEASE_DATE)=YEAR(GN.RELEASE_DATE)) #ofAdventureMovies,
(SELECT COUNT(DISTINCT TITLE) FROM #tmpGENRE WHERE GENRE LIKE 'Animation' AND YEAR(RELEASE_DATE)=YEAR(GN.RELEASE_DATE)) #ofAnimationMovies,
(SELECT COUNT(DISTINCT TITLE) FROM #tmpGENRE WHERE GENRE LIKE 'Comedy' AND YEAR(RELEASE_DATE)=YEAR(GN.RELEASE_DATE)) #ofComedyMovies,
(SELECT COUNT(DISTINCT TITLE) FROM #tmpGENRE WHERE GENRE LIKE 'Crime' AND YEAR(RELEASE_DATE)=YEAR(GN.RELEASE_DATE)) #ofCrimeMovies,
(SELECT COUNT(DISTINCT TITLE) FROM #tmpGENRE WHERE GENRE LIKE 'Documentary' AND YEAR(RELEASE_DATE)=YEAR(GN.RELEASE_DATE)) #ofDocumentaryMovies,
(SELECT COUNT(DISTINCT TITLE) FROM #tmpGENRE WHERE GENRE LIKE 'Drama' AND YEAR(RELEASE_DATE)=YEAR(GN.RELEASE_DATE)) #ofDramaMovies,
(SELECT COUNT(DISTINCT TITLE) FROM #tmpGENRE WHERE GENRE LIKE 'Family' AND YEAR(RELEASE_DATE)=YEAR(GN.RELEASE_DATE)) #ofFamilyMovies,
(SELECT COUNT(DISTINCT TITLE) FROM #tmpGENRE WHERE GENRE LIKE 'Fantasy' AND YEAR(RELEASE_DATE)=YEAR(GN.RELEASE_DATE)) #ofFantasyMovies,
(SELECT COUNT(DISTINCT TITLE) FROM #tmpGENRE WHERE GENRE LIKE 'History' AND YEAR(RELEASE_DATE)=YEAR(GN.RELEASE_DATE)) #ofHistoryMovies,
(SELECT COUNT(DISTINCT TITLE) FROM #tmpGENRE WHERE GENRE LIKE 'Horror' AND YEAR(RELEASE_DATE)=YEAR(GN.RELEASE_DATE)) #ofHorrorMovies,
(SELECT COUNT(DISTINCT TITLE) FROM #tmpGENRE WHERE GENRE LIKE 'Music' AND YEAR(RELEASE_DATE)=YEAR(GN.RELEASE_DATE)) #ofMusicMovies,
(SELECT COUNT(DISTINCT TITLE) FROM #tmpGENRE WHERE GENRE LIKE 'Mystery' AND YEAR(RELEASE_DATE)=YEAR(GN.RELEASE_DATE)) #ofMysteryMovies,
(SELECT COUNT(DISTINCT TITLE) FROM #tmpGENRE WHERE GENRE LIKE 'Romance' AND YEAR(RELEASE_DATE)=YEAR(GN.RELEASE_DATE)) #ofRomanceMovies,
(SELECT COUNT(DISTINCT TITLE) FROM #tmpGENRE WHERE GENRE LIKE 'Science Fiction' AND YEAR(RELEASE_DATE)=YEAR(GN.RELEASE_DATE)) #ofScienceFictionMovies,
(SELECT COUNT(DISTINCT TITLE) FROM #tmpGENRE WHERE GENRE LIKE 'TV Movie' AND YEAR(RELEASE_DATE)=YEAR(GN.RELEASE_DATE)) #ofTVMovieMovies,
(SELECT COUNT(DISTINCT TITLE) FROM #tmpGENRE WHERE GENRE LIKE 'Thriller' AND YEAR(RELEASE_DATE)=YEAR(GN.RELEASE_DATE)) #ofThrillerMovies,
(SELECT COUNT(DISTINCT TITLE) FROM #tmpGENRE WHERE GENRE LIKE 'War' AND YEAR(RELEASE_DATE)=YEAR(GN.RELEASE_DATE)) #ofWarMovies,
(SELECT COUNT(DISTINCT TITLE) FROM #tmpGENRE WHERE GENRE LIKE 'Action' AND YEAR(RELEASE_DATE)=YEAR(GN.RELEASE_DATE)) #ofWesternMovies

FROM
(
SELECT  G.GENRE,M.TITLE,M.ORIGINAL_TITLE,M.RELEASE_DATE 
FROM MOVIE M 
INNER JOIN MOVIE_GENRE MG ON MG.FILMID=M.FILMID
INNER JOIN GENRE G ON G.GENREID=MG.GENREID
--ORDER BY M.RELEASE_DATE DESC
) GN
GROUP BY YEAR(GN.RELEASE_DATE)
ORDER BY YEAR(GN.RELEASE_DATE) DESC
