SELECT 
	GP.GENRE Genre, 
	COUNT(GP.TITLE) #ofMovie, 
	SUM(GP.Profit) Profit,
	ROUND(AVG(GP.Profit),2) AvgProfit
FROM 
(
SELECT  G.GENRE,M.TITLE,M.ORIGINAL_TITLE,M.RELEASE_DATE,M.BUDGET,M.REVENUE, M.REVENUE-M.BUDGET AS Profit
FROM MOVIE M
INNER JOIN MOVIE_GENRE MG ON MG.FILMID=M.FILMID
INNER JOIN GENRE G ON G.GENREID=MG.GENREID
WHERE 
	M.BUDGET <> '0' AND 
	M.REVENUE <> '0'
) GP

GROUP BY GP.GENRE
ORDER BY 4 DESC