SELECT 
	TMP.CompanyName, 
	SUM(TMP.Profit) TotalProfit, 
	COUNT(TMP.MovieName) #ofMovie, 
	ROUND(AVG(TMP.Profit),2) AvgProfit 
FROM 
(
SELECT M.TITLE MovieName,M.ORIGINAL_TITLE OriginalMovieName,M.RELEASE_DATE,M.BUDGET,M.REVENUE, M.REVENUE-M.BUDGET AS Profit, C.NAME_ CompanyName
FROM MOVIE M
INNER JOIN MOVIE_COMPANY MC ON MC.FILMID=M.FILMID
INNER JOIN COMPANY C ON C.COMPANYID=MC.COMPANYID
WHERE M.BUDGET <> '0' AND M.REVENUE <> '0'
--AND C.NAME_ LIKE 'Colorado Office of Film, Television & Media'
--ORDER BY M.REVENUE DESC
) TMP
GROUP BY TMP.CompanyName
ORDER BY 3 DESC
